language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nuridavid/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true nuridavid/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "Docker-env.eba-npingyju.us-east-2.elasticbeanstalk.com"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-426788707955"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
